name: CVE Scanning for Maven

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/pom.xml'
      - '.cve/allow-list.xml'
      - '.github/workflows/cve-scanning.yml'
  pull_request:
    paths:
      - '**/pom.xml'
      - '.cve/allow-list.xml'
      - '.github/workflows/cve-scanning.yml'

jobs:
  depcheck:
    # Skip this job for release commits
    if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        java-package: jdk
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests
    - name: CVE scanning
      uses: dependency-check/Dependency-Check_Action@1b5d19fd4a32ff0ff982e8c9d8e27dbf7ac8a46c
      env:
        JAVA_HOME: /opt/jdk
      with:
        project: 'legend-engine-ide-lsp'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --suppression .cve/allow-list.xml
          --failOnCVSS 7
    - name: Upload Test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
          name: Depcheck report
          path: ${{ github.workspace }}/reports
