name: CVE Scanning for Maven

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'pom.xml'
      - 'allow-list.xml'
      - '.github/workflows/cve-scanning.yml'
  pull_request:
    paths:
      - 'pom.xml'
      - 'allow-list.xml'
      - '.github/workflows/cve-scanning.yml'

jobs:
  depcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests
    - name: CVE scanning
      uses: dependency-check/Dependency-Check_Action@1b5d19fd4a32ff0ff982e8c9d8e27dbf7ac8a46c
      env:
        JAVA_HOME: /opt/jdk
      with:
        project: 'legend-engine-ide-lsp'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --suppression allow-list.xml
          --failOnCVSS 7
    - name: Upload Test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
          name: Depcheck report
          path: ${{ github.workspace }}/reports
